# Configuration for Zuul Visualizer
# clone_dir: directory where repositories will be cloned. Defaults to 'repo_data'
# sources: list of git repository URLs

clone_dir: repo_data

# sources:
#   - https://your-zuul-repo

# AI Documentation Settings
# auto_generate_docs: if true, the scheduler will automatically generate documentation for new repos.
auto_generate_docs: false
doc_update_interval: 3600 # 1 hour
# enable_ai: true
# ai_auth_strategy: "env" # "env" or "file"
# gemini_api_key: "" # uncomment if using env strategy
# ai_model: "gemini-2.0-flash-lite-preview-02-05"
# gemini_auth_file: "/path/to/your/credentials.json" # uncomment if using file strategy